### PR TITLE
Move chef_wm_password to chef_objects/src/chef_password

### PR DESCRIPTION
**Pull request by marcparadise**
- remove chef_wm_password and tests from this repo
- also remove chef_wm_authenticate_user, _users, _named_users and routing to them -
  it makes no sense to update these to use the updated password module,
  since these have been superceded by oc_chef_wm versions of the same.

ping @opscode/server-team

### CODE REVIEW

**Comment by sdelano** [comment]
:thumbsup:

**Comment by jmink** [comment]
:+1: Assuming I'm understanding your comment correctly to mean this is all dead code.

**Comment by mmzyk** [comment]
Does the erchef and/or oc_erchef repo need an update to the rebar.config and rebar.config.lock file to ensure all the proper dependencies are pulled in? I just want to make sure chef_sked can find the new location in chef_objects

**Comment by marcparadise** [comment]
@mmzyk chef_wm has a dependency on chef_objects via rebar, so it will get all  necessary components.

**Pull request merged**
