### PR TITLE
Ss/experimental refactor

### PR DESCRIPTION
**Pull request by sersut**

### CODE REVIEW

**Comment by seth** [comment]
Overall I like the factoring out of the core search details from the wm resource module. +1

**Comment by halfss** [comment]
hi，
  what's the branch of chef_wm-0.01 inf chef 11(erchef)?

  thanks

**Comment by seth** [comment]
We use a rebar plugin to lock all of erchef's dependencies. You can find the version of chef_wm included in erchef on master here: https://github.com/opscode/erchef/blob/master/rebar.config.lock#L34

You can look at that file in erchef at a particular tag to determine what's included in a tag.

**Comment by marcparadise** [comment]
Too far out of sync, if we want to pull this in at any point we'd need to recreate against oc_erchef

**Pull request closed without merging**
