### PR TITLE
Surface authz_id via principals endpoint.

### PR DESCRIPTION
**Pull request by langloisjp**

### CODE REVIEW

**Comment by langloisjp** [comment]
Corresponding oc-chef-pedant change https://github.com/opscode/oc-chef-pedant/pull/6. Loaded and ran in dev vm successfully.

**Comment by langloisjp** [comment]
@seth Please review.

**Comment by seth** [comment]
This looks good to me. Once you've verified the OSC build via a full chef-pedant run with this code loaded in, MWR.

**Comment by langloisjp** [comment]
Loaded chef-server_11.0.0-alpha-9-g0209f77-1.ubuntu.10.04_amd64.deb in dev VM, then loaded erchef on top (with symlink to this chef_wm repo with the change). Ran chef-server-ctl test --all successfully.

**Comment by langloisjp** [comment]
Are you sure this can be merged without the accompanying pedant update? The current pedant repo without my change will probably break...

**Comment by seth** [comment]
So I'm confused. If you loaded the code and ran with the existing pedant tests and they passed... then there isn't test breakage. If you had to load chef-pedant, then it wasn't the intended test. When you say "current pedant repo" do you mean chef-pedant?

**Comment by langloisjp** [comment]
- OPC with my change and the accompanying pedant change: check.
- OSC with my change and no pedant change: check.
- OPC with my change but without the pedant change: probably breaks.

**Comment by seth** [comment]
Understood. Thanks. So then MWR here (e.g. once oc-chef-pedant change is reviewed and merged).

**Pull request merged**
